package DanceParty::Model::DB;
use strict;
use Config::General;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => DanceParty->config->{'Model::DBIC'}->{'schema_class'},
    connect_info => DanceParty->config->{'Model::DBIC'}->{'connect_info'},
);

=head1 NAME

DanceParty::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<DanceParty>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<DanceParty::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Raquel Bujans

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
